name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: jvalkeal/setup-java@gh40-work1
      with:
        java-version: 1.8
        maven-version: 3.6.1
        gradle-version: 5.6.2
        maven-file: packages/apache-maven-3.6.1-bin.tar.gz
        gradle-file: packages/gradle-5.6.2-bin.zip

    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.33.1
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}

    - name: maven home
      run: echo $M2_HOME

    - name: maven version
      run: mvn -v

    - name: gradle home
      run: echo $GRADLE_HOME

    - name: gradle version
      run: gradle -v
