name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set Maven
      uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.1

    - name: Set Gradle
      uses: jvalkeal/setup-gradle@v1
      with:
        gradle-version: 5.6.2

    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.36.0
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}

    - name: jfrog version
      run: jfrog -v

    - name: maven home
      run: echo $M2_HOME

    - name: maven version
      run: mvn -v

    - name: gradle home
      run: echo $GRADLE_HOME

    - name: gradle version
      run: gradle -v
