name: Release Train Test1

on:
  workflow_dispatch:
    inputs:
      prop21:
        description: 'prop21'
        required: false
        default: 'val21'
      prop41:
        description: 'prop41'
        required: false
        default: 'val41'
  repository_dispatch:
    types: [build-zoo-handler-control]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Do Something
      id: extract
      env:
        PROP21: ${{ github.event.inputs.prop21 }}
      run: echo ::set-output name=PROP21::${PROP21:-val21}

    - name: Fire jvalkeal/atest2
      uses: jvalkeal/build-zoo-handler@gh7-work1
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        # dispatch-handler-config: >
        #   [
        #     {
        #       "default": true,
        #       "owner": "jvalkeal",
        #       "repo": "atest4",
        #       "event_type": "build-zoo-handler-build"
        #     },
        #     {
        #       "on_event": "build-succeed",
        #       "on_owner": "jvalkeal",
        #       "on_repo": "atest4",
        #       "owner": "jvalkeal",
        #       "repo": "atest3",
        #       "event_type": "build-zoo-handler-build"
        #     },
        #     {
        #       "on_event": "build-succeed",
        #       "on_owner": "jvalkeal",
        #       "on_repo": "atest3",
        #       "owner": "jvalkeal",
        #       "repo": "atest2",
        #       "event_type": "build-zoo-handler-build"
        #     },
        #     {
        #       "on_event": "build-succeed",
        #       "on_owner": "jvalkeal",
        #       "on_repo": "atest2",
        #       "owner": "jvalkeal",
        #       "repo": "atest1",
        #       "event_type": "build-zoo-handler-build"
        #     }
        #   ]

    # "data": {
    #   "prop21": "${{ steps.extract.outputs.PROP21 }}"
    # }
